FROM ubuntu:24.04

# Install required dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl ca-certificates unzip \
    && rm -rf /var/lib/apt/lists/*

# Install Bun and nginx-light (without sudo)
RUN curl -fsSL https://bun.sh/install | bash \
    && apt-get update \
    && apt-get install -y --no-install-recommends nginx-light \
    && rm -rf /var/lib/apt/lists/*

COPY nginx.conf /etc/nginx/sites-available/default  
# Add Bun to PATH
ENV PATH="/root/.bun/bin:${PATH}"

WORKDIR /app
RUN bun create vite@latest my-app --template react-ts
WORKDIR /app/my-app
CMD ["/bin/bash"]
