/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserworkspacesRouteImport } from './routes/userworkspaces'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceUrlstringRouteImport } from './routes/workspace.$urlstring'
import { Route as ApiUseraiagentRouteImport } from './routes/api.useraiagent'
import { Route as ApiDemoNamesRouteImport } from './routes/api.demo-names'
import { Route as ApiCreatWorkspcaeUserIdRouteImport } from './routes/api.creatWorkspcae.$userId'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as ApiAiAgentRouteImport } from './routes/api.ai.agent'
import { Route as ApiMesagestoreUrlstringIdRouteImport } from './routes/api.mesagestore.$urlstring.$Id'

const UserworkspacesRoute = UserworkspacesRouteImport.update({
  id: '/userworkspaces',
  path: '/userworkspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceUrlstringRoute = WorkspaceUrlstringRouteImport.update({
  id: '/workspace/$urlstring',
  path: '/workspace/$urlstring',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUseraiagentRoute = ApiUseraiagentRouteImport.update({
  id: '/api/useraiagent',
  path: '/api/useraiagent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoNamesRoute = ApiDemoNamesRouteImport.update({
  id: '/api/demo-names',
  path: '/api/demo-names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreatWorkspcaeUserIdRoute = ApiCreatWorkspcaeUserIdRouteImport.update({
  id: '/api/creatWorkspcae/$userId',
  path: '/api/creatWorkspcae/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiAgentRoute = ApiAiAgentRouteImport.update({
  id: '/api/ai/agent',
  path: '/api/ai/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMesagestoreUrlstringIdRoute =
  ApiMesagestoreUrlstringIdRouteImport.update({
    id: '/api/mesagestore/$urlstring/$Id',
    path: '/api/mesagestore/$urlstring/$Id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/userworkspaces': typeof UserworkspacesRoute
  '/api/demo-names': typeof ApiDemoNamesRoute
  '/api/useraiagent': typeof ApiUseraiagentRoute
  '/workspace/$urlstring': typeof WorkspaceUrlstringRoute
  '/api/ai/agent': typeof ApiAiAgentRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/creatWorkspcae/$userId': typeof ApiCreatWorkspcaeUserIdRoute
  '/api/mesagestore/$urlstring/$Id': typeof ApiMesagestoreUrlstringIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/userworkspaces': typeof UserworkspacesRoute
  '/api/demo-names': typeof ApiDemoNamesRoute
  '/api/useraiagent': typeof ApiUseraiagentRoute
  '/workspace/$urlstring': typeof WorkspaceUrlstringRoute
  '/api/ai/agent': typeof ApiAiAgentRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/creatWorkspcae/$userId': typeof ApiCreatWorkspcaeUserIdRoute
  '/api/mesagestore/$urlstring/$Id': typeof ApiMesagestoreUrlstringIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/userworkspaces': typeof UserworkspacesRoute
  '/api/demo-names': typeof ApiDemoNamesRoute
  '/api/useraiagent': typeof ApiUseraiagentRoute
  '/workspace/$urlstring': typeof WorkspaceUrlstringRoute
  '/api/ai/agent': typeof ApiAiAgentRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/creatWorkspcae/$userId': typeof ApiCreatWorkspcaeUserIdRoute
  '/api/mesagestore/$urlstring/$Id': typeof ApiMesagestoreUrlstringIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/userworkspaces'
    | '/api/demo-names'
    | '/api/useraiagent'
    | '/workspace/$urlstring'
    | '/api/ai/agent'
    | '/api/auth/$'
    | '/api/creatWorkspcae/$userId'
    | '/api/mesagestore/$urlstring/$Id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/userworkspaces'
    | '/api/demo-names'
    | '/api/useraiagent'
    | '/workspace/$urlstring'
    | '/api/ai/agent'
    | '/api/auth/$'
    | '/api/creatWorkspcae/$userId'
    | '/api/mesagestore/$urlstring/$Id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/userworkspaces'
    | '/api/demo-names'
    | '/api/useraiagent'
    | '/workspace/$urlstring'
    | '/api/ai/agent'
    | '/api/auth/$'
    | '/api/creatWorkspcae/$userId'
    | '/api/mesagestore/$urlstring/$Id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  UserworkspacesRoute: typeof UserworkspacesRoute
  ApiDemoNamesRoute: typeof ApiDemoNamesRoute
  ApiUseraiagentRoute: typeof ApiUseraiagentRoute
  WorkspaceUrlstringRoute: typeof WorkspaceUrlstringRoute
  ApiAiAgentRoute: typeof ApiAiAgentRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCreatWorkspcaeUserIdRoute: typeof ApiCreatWorkspcaeUserIdRoute
  ApiMesagestoreUrlstringIdRoute: typeof ApiMesagestoreUrlstringIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/userworkspaces': {
      id: '/userworkspaces'
      path: '/userworkspaces'
      fullPath: '/userworkspaces'
      preLoaderRoute: typeof UserworkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$urlstring': {
      id: '/workspace/$urlstring'
      path: '/workspace/$urlstring'
      fullPath: '/workspace/$urlstring'
      preLoaderRoute: typeof WorkspaceUrlstringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/useraiagent': {
      id: '/api/useraiagent'
      path: '/api/useraiagent'
      fullPath: '/api/useraiagent'
      preLoaderRoute: typeof ApiUseraiagentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo-names': {
      id: '/api/demo-names'
      path: '/api/demo-names'
      fullPath: '/api/demo-names'
      preLoaderRoute: typeof ApiDemoNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/creatWorkspcae/$userId': {
      id: '/api/creatWorkspcae/$userId'
      path: '/api/creatWorkspcae/$userId'
      fullPath: '/api/creatWorkspcae/$userId'
      preLoaderRoute: typeof ApiCreatWorkspcaeUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/agent': {
      id: '/api/ai/agent'
      path: '/api/ai/agent'
      fullPath: '/api/ai/agent'
      preLoaderRoute: typeof ApiAiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mesagestore/$urlstring/$Id': {
      id: '/api/mesagestore/$urlstring/$Id'
      path: '/api/mesagestore/$urlstring/$Id'
      fullPath: '/api/mesagestore/$urlstring/$Id'
      preLoaderRoute: typeof ApiMesagestoreUrlstringIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  UserworkspacesRoute: UserworkspacesRoute,
  ApiDemoNamesRoute: ApiDemoNamesRoute,
  ApiUseraiagentRoute: ApiUseraiagentRoute,
  WorkspaceUrlstringRoute: WorkspaceUrlstringRoute,
  ApiAiAgentRoute: ApiAiAgentRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCreatWorkspcaeUserIdRoute: ApiCreatWorkspcaeUserIdRoute,
  ApiMesagestoreUrlstringIdRoute: ApiMesagestoreUrlstringIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
